apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: loanhub
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://loanhub-dev.c25euos0um47.us-east-1.rds.amazonaws.com:5432/loanhub_dev"
  SPRING_DATASOURCE_USERNAME: "loanhub"
  APP_CORS_ALLOWED_ORIGINS: "https://loanhub.example.com"
